config:
  credentials: []
  project_repos:
    github.com/ARGOeu/eosc-recommender-metrics:
      branch: master
      repo: https://github.com/ARGOeu/eosc-recommender-metrics
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-lemon-sloth.sh
        container: qc.acc_sleepy-xanthic-wombat
  QC.Doc:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-thistle-spaniel.sh
        container: qc.doc_snazzy-mauve-lemming
      github.com/ARGOeu/eosc-recommender-metrics git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-wheat-newt.sh
        container: qc.doc_squirrely-cinnabar-dogfish
      github.com/ARGOeu/eosc-recommender-metrics markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-green-moth.sh
        container: qc.doc_chewy-linen-maltese
  QC.Lic:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics licensee:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-beige-skunk.sh
        container: qc.lic_nerdy-aqua-giraffe
  QC.Met:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.beady-mustard-fousek.sh
        container: qc.met_crabby-brass-badger
  QC.Sec:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics bandit:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-eggplant-penguin.sh
        container: qc.sec_pretty-zucchini-grasshopper
  QC.Sty:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics flake8:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-grey-jaguar.sh
        container: qc.sty_crabby-sangria-wolfhound
      github.com/ARGOeu/eosc-recommender-metrics jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-wheat-harrier.sh
        container: qc.sty_stinky-goldenrod-caterpillar
  QC.Ver:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-pear-horse.sh
        container: qc.ver_freaky-orange-raccoon
timeout: 5400
