config:
  credentials: []
  project_repos:
    github.com/ARGOeu/eosc-recommender-metrics:
      branch: master
      repo: https://github.com/ARGOeu/eosc-recommender-metrics
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics git:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-grey-jaguar.sh
        container: qc.acc_crabby-tan-wolverine
  QC.Doc:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-pumpkin-chinchilla.sh
        container: qc.doc_pokey-azure-terrier
      github.com/ARGOeu/eosc-recommender-metrics git:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-mauve-coral.sh
        container: qc.doc_woolly-lavender-boar
      github.com/ARGOeu/eosc-recommender-metrics markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-emerald-fousek.sh
        container: qc.doc_scanty-plum-forest
  QC.Lic:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-lilac-kudu.sh
        container: qc.lic_sunny-teal-otter
  QC.Met:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-mustard-crocodile.sh
        container: qc.met_bluesy-aqua-schnauzer
  QC.Sec:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-flax-hyena.sh
        container: qc.sec_muggy-mustard-beagle
  QC.Sty:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics flake8:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-auburn-mist.sh
        container: qc.sty_lanky-teal-tuatara
      github.com/ARGOeu/eosc-recommender-metrics jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-grey-tuatara.sh
        container: qc.sty_shabby-russet-catfish
  QC.Ver:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-corn-ocelot.sh
        container: qc.ver_scummy-lemon-dachsbracke
timeout: 5400
